### ISSUE TITLE
String in BasicCommands

### ISSUE THREAD

**Issue by Enc-int** [CreativeRobotics/Commander#14]
I've tried several times to use the string as output in BasicCommands for an if function. First, I was told that the variable myString was not defined in the code, so I initialized String myString=""; as with float and int. However, I wasn't able to print myString and the if function wasn't working, so the code wasn't able to show me whether the string was set to the right value. I made a thread about this on the arduino forum and b707 helped me. It seems that initializing the string in BasicCommands is the correct way to use it in this code, but it has already been initialized in the Master, which would block the string from being modified in BasicCommands. The solution was to comment out the initialization in the Master, and it worked!
https://forum.arduino.cc/t/commander-library-set-string/1188811/12

`/*Commander example - basic
 * Demonstrating commands to get and set an int and a float
 
#include <Commander.h>
Commander cmd;
//Variables we can set or get
int myInt = 0;
float myFloat = 0.0;
String myString="";

String deviceInfo = "#\tCommander basic commands example\n#\thttps://github.com/CreativeRobotics/Commander";
//SETUP ---------------------------------------------------------------------------
void setup() {
  Serial.begin(115200);
  initialiseCommander();
  while(!Serial){;}
  cmd.printUserString();
  cmd.println();
  Serial.println("Type 'help' to get help");
  cmd.printCommandPrompt();
}

//MAIN LOOP ---------------------------------------------------------------------------
void loop() {

//command=cmd.getPayloadString();

  if(myString =="stop"){
  Serial.println("Succes string");
}
  else if(myString=="go") {
 Serial.println("Succes go");
}
  cmd.update();
}
  //Serial.println(myInt);
`

`//All commands for 'master'
//COMMAND ARRAY ------------------------------------------------------------------------------
const commandList_t masterCommands[] = {
  {"hello",       helloHandler,     "hello"},
  {"get int",     getIntHandler,    "get an int"},
  {"set int",     setIntHandler,    "set an int"},
  {"get float",   getFloatHandler,  "get a float"},
  {"set float",   setFloatHandler,  "set a float"},
  {"hidden1",     hiddenHandler,    "-Command hidden from help"},
  {"myint",       setIntHandler,    "try myint=23"},
  {"myfloat",     setFloatHandler,  "try myfloat=23.5"},
  {"set ints",    setIntsHandler,   "set up to four ints"},
  {"set floats",  setFloatsHandler, "set up to four floats"},
  {"set strings", setStringsHandler,"set up to four Strings"},
  {"hidden2",     hiddenHandler,    "-Command hidden from help"},
};

/* Command handler template
bool myFunc(Commander &Cmdr){
  //put your command handler code here
  return 0;
}
*/
void initialiseCommander(){
  cmd.begin(&Serial, masterCommands, sizeof(masterCommands));
  cmd.commandPrompt(ON); //enable the command prompt
  cmd.echo(true);     //Echo incoming characters to theoutput port
  cmd.errorMessages(ON); //error messages are enabled - it will tell us if we issue any unrecognised commands
  cmd.autoChain(ON);
  cmd.setUserString(deviceInfo);
}

//These are the command handlers, there needs to be one for each command in the command array myCommands[]
//The command array can have multiple commands strings that all call the same function
bool helloHandler(Commander &Cmdr){
  Cmdr.print("Hello! this is ");
  Cmdr.println(Cmdr.commanderName);
  Cmdr.print("This is my buffer: ");
  Cmdr.print(Cmdr.bufferString);
  //Cmdr.printDiagnostics();
  return 0;
}
bool getIntHandler(Commander &Cmdr){
  Cmdr.print("myInt = ");
  Cmdr.println(myInt);
  //Cmdr.printDiagnostics();
  return 0;
}

bool setIntHandler(Commander &Cmdr){
  if(Cmdr.getInt(myInt)){
    Cmdr.print("myInt set to ");
    Cmdr.println(myInt);
  }
  //Cmdr.printDiagnostics();
  return 0;
}
bool getFloatHandler(Commander &Cmdr){
  Cmdr.print("myFloat = ");
  Cmdr.println(myFloat);
  
  //Cmdr.printDiagnostics();
  return 0;
}

bool setFloatHandler(Commander &Cmdr){
  if(Cmdr.getFloat(myFloat)){
    Cmdr.print("myFloat set to ");
    Cmdr.println(myFloat, 4); //print with 4 decimal places
  }
  //Cmdr.printDiagnostics();
  return 0;
}

bool setIntsHandler(Commander &Cmdr){
  //create an array to store any values we find
  int values[4] = {0,0,0,0};

  int itms = Cmdr.countItems();
  Cmdr.print("There are ");
  Cmdr.print(itms);
  Cmdr.println(" items in the payload");
  
  for(int n = 0; n < 4; n++){
    //try and unpack an int, if it fails there are no more left so exit the loop
    if(Cmdr.getInt(values[n])){
      Cmdr.print("unpacked ");
      Cmdr.println(values[n]);
    }else break;
  }
  //print it out
  Cmdr.println("Array contents after processing:");
  for(int n = 0; n < 4; n++){
    Cmdr.print(n);
    Cmdr.print(" = ");
    Cmdr.println(values[n]);
  }
  //Cmdr.chain();
  //Cmdr.printDiagnostics();
  return 0;
}

bool setFloatsHandler(Commander &Cmdr){
  float values[4] = {0.0,0.0,0.0,0.0};
  int itms = Cmdr.countItems();
  Cmdr.print("There are ");
  Cmdr.print(itms);
  Cmdr.println(" items in the payload");
  
  for(int n = 0; n < 4; n++){
    if(Cmdr.getFloat(values[n])){
      Cmdr.print("unpacked ");
      Cmdr.println(values[n]);
    }else break;
  }
  Cmdr.println("Array contents after processing:");
  for(int n = 0; n < 4; n++){
    Cmdr.print(n);
    Cmdr.print(" = ");
    Cmdr.println(values[n]);
  }
  //Cmdr.chain();
  //Cmdr.printDiagnostics();
  return 0;
}

bool setStringsHandler(Commander &Cmdr){
  //String myString = "";
  int itms = Cmdr.countItems();
  Cmdr.print("There are ");
  Cmdr.print(itms);
  Cmdr.println(" items in the payload");
  for(int n = 0; n < itms; n++){
    if(Cmdr.getString(myString)){
      Cmdr.print("String ");
      Cmdr.print(n);
      Cmdr.print(" = ");
      Cmdr.println(myString);
    }else Cmdr.println("Operation failed");
  }
  //Cmdr.chain();
  //Cmdr.printDiagnostics();
  return 0;
}

bool hiddenHandler(Commander &Cmdr){
  Cmdr.println("This command is hidden from the help system");
  //Cmdr.printDiagnostics();
  return 0;
}`

**Comment by CreativeRobotics** [comment]
I'm not entirely clear what the issue is here.

myString is declared inside a handler, and is local to that handler - i.e. it isn't visible or useable to anything outside it.

If you declare it at the start of the sketch then you are making it a global variable, visible to everything, so you can't also declare the same variable in the handler -- If you want to use it outside the handler then comment out the declaration inside the handler otherwise the compiler sees two variable with the same name existing in the same 'name space' and it gets confused.

In the code you posted, the main loop repeatedly checks the variable myString, and it will contain whatever was in the last 'set strings' command.

If you want to access the payload that is in commander from the last command (not just the set strings command) then your code in loop should look like this:

```
String lastCommand=cmd.getPayloadString();

if(lastCommand=="stop"){
  Serial.println("Succes string");
}
else if(lastCommand=="go") {
  Serial.println("Succes go");
}
cmd.update();
```

But this isn't a good way to do things because if either of those strings are in the payload then it will print out the message over and over again as fast as it can until you send a command that doesn't have either of those words in the payload - Remember: the payload from the last command stays there in memory until it is overwritten when a new command arrives.

If your intention is to have an actual command called 'stop' and 'go' - so all you have to do is type stop or go - then make a new pair of handlers and commands. If you want to do something with the result in the main loop, use global flags to communicate the fact that a command has been handled:

First, add these lines to the command list:
```
{"stop",     stopHandler,    "Stop"},
{"go",     goHandler,    "Go"},
```

Next, add these two handlers:

```
bool stopHandler(Commander &Cmdr){
  Cmdr.println("STOP Command");
  stopCommand = true;
  return 0;
}

bool goHandler(Commander &Cmdr){
  Cmdr.println("GO Command");
  goCommand = true;
  return 0;
}
```

Now add these two lines above the setup() function (These are global variables so they are visible to everything in your whole sketch):

```
bool stopCommand = false;
bool goCommand = false;
```

Finally use this main loop (and put whatever else you need in there):

```
void loop() {
  cmd.update();
  if(stopCommand){
    stopCommand = false; //reset the flag so this only happens once for every command event
    Serial.println("Succes stop");
    //do other things that should happen when the stop command comes in ...
  }
  if(goCommand){
    goCommand = false; //reset the flag so this only happens once for every command event
    Serial.println("Succes go");
    //do other things that should happen when the go command comes in ...
  }
}
```

Remember, you can also put all the things you want to happen on a stop or go command inside the handler itself, and also call other functions from within the handlers.
