### ISSUE TITLE
endOfLineChar(CR) should also disable stripCR()?

### ISSUE THREAD

**Issue by embedded-creations** [CreativeRobotics/Commander#7]
My terminal uses CR as the default EOL character, and I've not had a problem with that setting for years, so I didn't feel like changing it to LF when trying out Commander.  I found `endOfLineChar()` but it didn't work when I changed to CR, and it took some digging to find the `stripCR()` method.

I think it's probably a common use case to want to change the EOL character to CR, would it be reasonable to automatically disable the stripCR setting if EOL is set to CR?

**Comment by CreativeRobotics** [comment]
I had a look through the code and found a few places where it wasn't properly referencing the end of line variable (it still had a hard coded '\n') so I fixed those bugs. I may have introduced a different issue though because of how printing works ...

I think the question is: should the end of line variable only apply to incoming data, or should it be applied to outgoing data as well? I am inclined to think not, because of the way Arduino puts a LF when using println().

Updating stripCR automatically when end of line is set to CR is a good suggestion so its implimented in the latest release.

Thanks.

**Comment by embedded-creations** [comment]
Thanks for the quick fix!

> should it be applied to outgoing data as well?

Maybe this isn't what you're asking, but I did notice that what I type in the prompt is overwritten by the response.  I have a feeling that's because I'm not sending a LF so a LF isn't echoed back before the response is sent.  I haven't investigated this yet, or looked for a solution that you've possibly already implemented as a setting.

**Comment by CreativeRobotics** [comment]
That sounds like behaviour at the terminal end rather than anything to do with Commander. What terminal application do you normally use?

**Comment by embedded-creations** [comment]
I use Serial (1.4.2) on the Mac, but I don't think it's a terminal-specific issue.  I'll do some more investigation and can open a new issue if you want to close this one for now.
